# Travis CI credentials

language: scala

scala:
 - "2.10.5"
 - "2.11.6"

sudo: false

# Emails to notify
notifications:
  slack:
    - websudos:P9QNXx1ZGFnDHp3v3jUqtB8k
  email:
    - dev@websudos.co.uk
jdk:
  - oraclejdk7
  - openjdk7

cache:
  directories:
    - $HOME/.ivy2/cache

before_script: travis_retry sbt ++$TRAVIS_SCALA_VERSION update


script:
  - sbt test
